name: build
on:
  pull_request:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    uses: victorfaurschou/minecraft-mod-workflows/.github/workflows/build.yml@main
    secrets: inherit
